server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/server_db
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  cache:
    disabled: true

logging:
  config: classpath:logback-spring-local.xml